//
//  PointCloudFile.swift
//
//  点群（Object Capture が位置合わせの過程で作る色つき 3D 点の集まり）を
//  ファイルへ書き出す層。値型とバイト列の組み立ては純ロジックなので、GPU も
//  RealityKit も無い環境で単体テストできる。
//
//  RealityKit の PhotogrammetrySession.PointCloud をそのまま扱わないのは、
//  「RealityKit の型は PhotogrammetryEngine.swift の外へ漏らさない」という
//  約束（CLAUDE.md）を守るため。エンジンが RealityKit の点をこの自前の値型へ
//  写してから渡す。
//
//  形式は PLY（binary_little_endian 1.0）1 つだけにしてある:
//    - 点群の交換形式として最も広く読める（CloudCompare・MeshLab・各種 CAD）。
//    - 建築規模では点が数百万になるため、テキスト形式（ascii PLY・xyz）では
//      ファイルサイズも書き出し時間も実用にならない。
//  したがって出力ファイルの拡張子は .ply に固定する（ReconstructionRequest の
//  validate が弾く）。
//

import Foundation

/// 点群を構成する点 1 つ。位置（メートル・モデルのローカル座標系）と色を持つ。
///
/// RealityKit の `PhotogrammetrySession.PointCloud.Point` と 1:1 に対応するが、
/// 依存を持ち込まないために自前で定義している。
public struct PointCloudPoint: Equatable, Sendable
{
	public var x: Float
	public var y: Float
	public var z: Float
	public var red: UInt8
	public var green: UInt8
	public var blue: UInt8
	/// 不透明度。Object Capture は常に 255 を返すが、PLY の慣例に合わせて持つ。
	public var alpha: UInt8

	public init(
		x: Float,
		y: Float,
		z: Float,
		red: UInt8,
		green: UInt8,
		blue: UInt8,
		alpha: UInt8 = 255)
	{
		self.x = x
		self.y = y
		self.z = z
		self.red = red
		self.green = green
		self.blue = blue
		self.alpha = alpha
	}
}

/// 点群の PLY ファイルへの書き出し。
public enum PointCloudFile
{
	/// 出力ファイルの拡張子（形式は PLY 固定）。
	public static let fileExtension = "ply"

	/// 1 点あたりのバイト数（float x/y/z + uchar r/g/b/a）。ヘッダの
	/// property 宣言と対になっているので、片方を変えるときは両方を変える。
	public static let bytesPerPoint = 16

	/// 一度に組み立てる点の数。数百万点ぶんの Data を一気に作るとピーク
	/// メモリが跳ねるので、この単位で書き出す。
	static let chunkSize = 65536

	/// PLY のヘッダ。末尾は改行で終わり、直後からバイナリ本体が始まる。
	public static func header(pointCount: Int) -> String
	{
		"""
		ply
		format binary_little_endian 1.0
		comment Generated by Photogrammetry (Object Capture)
		element vertex \(pointCount)
		property float x
		property float y
		property float z
		property uchar red
		property uchar green
		property uchar blue
		property uchar alpha
		end_header

		"""
	}

	/// ファイル全体のバイト列。点数が少ないとき（テスト・小さな対象）向け。
	/// 大量の点は `write(points:to:)` を使う（そちらは分割して書き出す）。
	public static func data(points: [PointCloudPoint]) -> Data
	{
		var result = Data(header(pointCount: points.count).utf8)
		result.append(body(points[...]))
		return result
	}

	/// 点群を PLY ファイルとして書き出す。既存のファイルは置き換える。
	public static func write(
		points: [PointCloudPoint],
		to url: URL,
		fileManager: FileManager = .default) throws
	{
		// 出力先の親フォルダが無いことがある（利用者が手で組み立てたパス）。
		try fileManager.createDirectory(
			at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
		// 空のファイルを作り直してから（既存の内容は捨てる）、ヘッダ・本体の順に
		// 書いていく。フォルダを指定されたときはここで false が返る。
		guard fileManager.createFile(atPath: url.path, contents: nil)
		else
		{
			throw PointCloudError.cannotWrite(url.path)
		}

		let handle = try FileHandle(forWritingTo: url)
		defer
		{
			try? handle.close()
		}
		try handle.write(contentsOf: Data(header(pointCount: points.count).utf8))
		var index = points.startIndex
		while index < points.endIndex
		{
			let upperBound = min(index + chunkSize, points.endIndex)
			try handle.write(contentsOf: body(points[index ..< upperBound]))
			index = upperBound
		}
	}

	/// 点の並びをバイナリ本体へ変換する。
	static func body(_ points: ArraySlice<PointCloudPoint>) -> Data
	{
		var data = Data()
		data.reserveCapacity(points.count * bytesPerPoint)
		for point in points
		{
			append(point.x, to: &data)
			append(point.y, to: &data)
			append(point.z, to: &data)
			data.append(point.red)
			data.append(point.green)
			data.append(point.blue)
			data.append(point.alpha)
		}
		return data
	}

	/// float を 4 バイトのリトルエンディアンとして書く。ヘッダで
	/// binary_little_endian を宣言している以上、実行環境のバイト順に関わらず
	/// この順で並べなければならないので、シフトで明示的に組み立てる。
	private static func append(_ value: Float, to data: inout Data)
	{
		let bits = value.bitPattern
		data.append(UInt8(truncatingIfNeeded: bits))
		data.append(UInt8(truncatingIfNeeded: bits >> 8))
		data.append(UInt8(truncatingIfNeeded: bits >> 16))
		data.append(UInt8(truncatingIfNeeded: bits >> 24))
	}
}

public enum PointCloudError: Error, LocalizedError, Equatable
{
	case cannotWrite(String)

	public var errorDescription: String?
	{
		switch self
		{
			case .cannotWrite(let path):
				return "点群ファイルを作成できません: \(path)"
		}
	}
}
